name: "Build"

on:
  push:
    branches:
      - main
    paths:
      - '**.java'
      - '**.kt'
      - '.github/workflows/build.yml'
      - 'pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Set short git commit SHA'
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: 'Checkout badges branch'
        uses: actions/checkout@v4
        with:
          ref: badges
          path: badges

      - name: 'Set up JDK 11'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: 'Build with Maven'
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Generate JaCoCo badges'
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          badges-directory: badges
          generate-branches-badge: true
          generate-summary: true

      - name: 'Upload JaCoCo coverage report as a workflow artifact'
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: 'Commit and push the coverage badges and summary file'
        run: |
          cd badges
          if [[ `git status --porcelain *.svg *.json` ]]; then
            git config --global user.name 'github-actions[bot]'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add *.svg *.json
            git commit -m "Autogenerated JaCoCo coverage badges for commit ${{ env.COMMIT_SHORT_SHA }}" *.svg *.json
            git push
          fi
