name: Java Katas Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Katas tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: mvn -B package

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branches = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name != 'pull_request' }}
        run: |
            cd .github/badges
            if [[ `git status --porcelain *.svg` ]]; then
              git config --global user.name 'github-actions'
              git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
              git add *.svg
              git commit -m "[skip ci] Autogenerated JaCoCo coverage badge" *.svg
              git push
            fi
