name: Pull Request validation and Snapshot build

on:
  pull_request

jobs:
  build:
    name: Pull Request Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Validate
        run: mvn -B verify

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          # fail-if-coverage-less-than: 75
          # fail-if-branches-less-than: 50
          generate-summary: true

      - name: PR body build
        id: pr_body_build
        if: success() || failure()
        run: |
          REPORT=$(<.github/badges/coverage-summary.json)
          COVERAGE=$(jq -r '.coverage' <<< "$REPORT")%
          BRANCHES=$(jq -r '.branches' <<< "$REPORT")%
          NEWLINE=$'\n'
          BODY="## JaCoCo Test Coverage Summary Statistics${NEWLINE}* __Coverage:__ ${COVERAGE}${NEWLINE}* __Branches:__ ${BRANCHES}"
          echo ${BODY}
          echo "COMMENT_BODY=${BODY}" >> $GITHUB_OUTPUT
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment PR
        if: success() || failure()
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ${{ steps.pr_body_build.outputs.COMMENT_BODY }}

      - name: Log coverage percentage
        if: success() || failure()
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branches = ${{ steps.jacoco.outputs.branches }}"

  publish-snapshot:
    name: Publish SNAPSHOT build
    needs: build
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: maven

      - name: Publish SNAPSHOT version
        run: mvn -B deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
