name: Release new version

on:
  workflow_dispatch:

jobs:
  release:
    name: 'Release'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Install SSH Client'
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 'Set up JDK 17'
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-id: 'github'

      - name: Configure Git user
        run: |
          git config user.email "release@mail.com"
          git config user.name "Maven Release"

      - name: 'Publish new version'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B release:prepare release:perform
